huge changes to neovim config

diff --git a/.local/scripts/ctldb b/.local/scripts/ctldb
--- a/.local/scripts/ctldb
+++ b/.local/scripts/ctldb
@@ -14,6 +14,32 @@ case "$1" in
       MariaDB service"
     fi
     ;;
+  post)
+    systemctl status postgresql | grep -q "inactive"
+    if [[ $? -eq 0 ]]; then
+      sudo systemctl enable --now postgresql
+      [[ $? -eq 0 ]] && echo "Restarting Postgres service" || echo "Cannot
+      restart Postgres service"
+    else
+      sudo systemctl stop postgresql
+      sudo systemctl disable postgresql
+      [[ $? -eq 0 ]] && echo "Stopping Postgres service" || echo "Cannot stop
+      Posrgres service"
+    fi
+    ;;
+  redis)
+    systemctl status redis | grep -q "inactive"
+    if [[ $? -eq 0 ]]; then
+      sudo systemctl enable --now redis
+      [[ $? -eq 0 ]] && echo "Restarting Redis service" || echo "Cannot
+      restart Redis service"
+    else
+      sudo systemctl stop redis
+      sudo systemctl disable redis
+      [[ $? -eq 0 ]] && echo "Stopping Redis service" || echo "Cannot stop
+      Redis service"
+    fi
+    ;;
   *)
     echo "I don't know what to do?"
     exit 1
